web_codes/ordov/urls.py
from django.contrib import admin
from django.urls import include, path
from candidates import views as candidatesViews
from resumes import views as resumesViews
from accounts import views as accountsViews
from companies import views as companiesViews
from interviews import views as interviewsViews
from experiences import views as experiencesViews
from permissions import views as permissionsViews

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'resumes', resumesViews.ResumeViewSet)
router.register(r'candidates', candidatesViews.CandidateViewSet)
router.register(r'posts', companiesViews.PostViewSet)
router.register(r'interviews', interviewsViews.InterviewViewSet)
router.register(r'experiences', experiencesViews.ExperienceViewSet)
router.register(r'educations', resumesViews.EducationViewSet)
router.register(r'projects', experiencesViews.ProjectViewSet)
router.register(r'languages', experiencesViews.LanguageViewSet)
router.register(r'certifications', experiencesViews.CertificationViewSet)
router.register(r'permissions', permissionsViews.ProjectPermissionViewSet)
router.register(r'accounts', accountsViews.UserProfileViewSet)
router.register(r'tags', resumesViews.TagViewSet)

# Look at here: all path pattern should be ENDUP with '/'
urlpatterns = [
    path('accounts/signup/', accountsViews.signup, name='accounts_signup'),
    path('accounts/signin/', accountsViews.signin, name='accounts_signin'),
    path('process/', accountsViews.process, name='process'),
    path('accounts/login/', accountsViews.MyLoginView.as_view(), name='login'),
    path('accounts/', include('allauth.urls')),
    path('api/v1/getResult', interviewsViews.aiTest),
    path('candidates/resume/update/', candidatesViews.updateResume, name='candidate_update_resume'),
    path('candidates/resume/success/', candidatesViews.apply_success, name='candidate_apply_success'),

    path('admin/', admin.site.urls),

    path('', include('landing_page.urls')),

    path('manager/', include('recruit_manager.urls'), name='manager'),
    path('company/', include('recruit_company.urls'), name='company'),
    path('applicant/', include('recruit_applicant.urls'), name='applicant'),

    path('api/', include(router.urls)),
    path('post/post/update/', companiesViews.UpdatePost),
    path('interview/ai/update/', interviewsViews.UpdateAIStatus),
    path('interview/ai/task/', interviewsViews.Task),
    path('interview/ai/info/', interviewsViews.getAIInfo),

    path('interviews/', include('interviews.urls'))
]

web_codes/recruit_manager/urls.py
from django.urls import path

from recruit_manager import views
from resumes import views as resumesViews
from companies import views as companiesViews
from interviews import views as interviewsViews

app_name = 'app_manager'

# Look at Here!! : All path pattern should be ENDUP with '/'
urlpatterns = [
    # ex: /manager/
    path('', views.index, name='t_index'), # t_index will be used in template
    path('upload/', views.upload, name='t_upload'),
    path('candidates/', views.CandidateTable.as_view(), name='t_candidates'),

    path('interviews/', interviewsViews.InterviewTable.as_view(), name='t_interviews'),

    path('interview-api/<int:resume_id>/<int:interview_id>/', views.interview_api, name='t_interview_api'),
    path('interview-result/<int:interview_id>/', views.interview_result, name='t_interview_result'),

    path('invitation-api/<int:resume_id>/', views.invitation_api, name='t_invitation_api'),
    path('invitation-result/<int:resume_id>/', views.invitation_result, name='t_invitation_result'),
    path('resumes/statistic/<int:post_id>/', views.resume_statistic, name='t_resume_statistic'),


    path('resumes/', resumesViews.ResumeTable.as_view(), name='t_resumes'),
    path('multi/', resumesViews.MultiTable.as_view(), name='t_multi'),
    path('multi/callInterview', views.callInterview, name='t_callInterview'),
    path('multi/test', views.callInterview, name='t_callInterview'),
    path('composite/', resumesViews.CompositeTable.as_view(), name='t_composite'),
    path('resumes/<int:pk>/', resumesViews.ResumeDetailInfo, name='t_resume'),
    path('resumes/<int:pk>/edit/', resumesViews.ResumeDetailInfo, name='t_resume_edit'),
    path('posts/', companiesViews.PostTable.as_view(), name='t_posts'),
]

web_codes/resumes/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from .choices import (BIRTH_YEAR_CHOICES, MAJOR_CHOICES, MARRIAGE_CHOICES, EDUCATION_TYPE_CHOICES)
from ordov.choices import (DEGREE_CHOICES, DEGREE_CHOICES_MAP, HUNTING_STATUS_CHOICES, HUNTING_STATUS_CHOICES_MAP)
from candidates.models import Candidate
from model_utils import Choices
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from companies.models import Post

# Create your models here.

class Resume(models.Model):
    # The Resume would be linked to a candidate afterwards
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, blank=True, null=True)
    resume_id = models.IntegerField(null=True)
    visible = models.BooleanField(default=False)
    resume_way = models.CharField(max_length=20, blank=True, null=True)
    resume_way2 = models.CharField(max_length=20, blank=True, null=True)

    # base info
    username = models.CharField(max_length=10, blank=True, null=True)
    gender = models.CharField(choices=(("m", "男"), ("f", "女"),), max_length=1, blank=True, null=True)
    birth_year = models.CharField(max_length=4, blank=True, null=True, choices=BIRTH_YEAR_CHOICES)
    birth_month = models.CharField(max_length=4, blank=True, null=True)
    birth_day = models.CharField(max_length=4, blank=True, null=True)
    date_of_birth = models.DateTimeField(blank=True, null=True)
    identity = models.CharField(max_length=25, blank=True, null=True)
    age = models.IntegerField(null=True)

    # birth place (jiguan in chinese)
    birth_province = models.CharField(max_length=10, blank=True, null=True)
    birth_city = models.CharField(max_length=10, blank=True, null=True)
    birth_district = models.CharField(max_length=10, blank=True, null=True)
    birth_street = models.CharField(max_length=10, blank=True, null=True)
    birth_place = models.CharField(max_length=50, blank=True, null=True)

    # social info
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    qq = models.BigIntegerField(null=True, blank=True)
    residence = models.CharField(max_length=50, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    marriage = models.CharField(max_length=10, blank=True, null=True, choices=MARRIAGE_CHOICES)
    live_state = models.CharField(max_length=10, blank=True, null=True)

    # resident info
    current_settle_province = models.CharField(max_length=10, blank=True, null=True)
    current_settle_city = models.CharField(max_length=10, blank=True, null=True)
    current_settle_district = models.CharField(max_length=10, blank=True, null=True)
    current_settle_street = models.CharField(max_length=20, blank=True, null=True)

    # Expection info
    expected_industry = models.CharField(max_length=50, null=True, blank=True)
    expected_salary = models.CharField(max_length=50, null=True, blank=True)
    expected_post = models.CharField(max_length=50, null=True, blank=True)
    expected_positon = models.CharField(max_length=50, null=True, blank=True)
    expected_restmodel = models.CharField(max_length=50, null=True, blank=True)
    expected_insurance_place_type = models.CharField(max_length=50, null=True, blank=True)
    expected_insurance_time_type = models.CharField(max_length=50, null=True, blank=True)

    expected_province = models.CharField(max_length=50, null=True, blank=True)
    expected_city = models.CharField(max_length=50, null=True, blank=True)
    expected_district = models.CharField(max_length=50, null=True, blank=True)
    expected_street = models.CharField(max_length=50, null=True, blank=True)

    # education related
    degree = models.IntegerField(blank=True, null=True, choices=DEGREE_CHOICES)
    major = models.CharField(max_length=30, blank=True, null=True)
    school = models.CharField(max_length=30, blank=True, null=True)
    graduate_time = models.CharField(max_length=30, blank=True, null=True)
    graduate_year = models.IntegerField(null=True, blank=True)

    # Text Fieled
    self_description = models.TextField(max_length=500, blank=True, null=True, default='')

    # reserved Field
    reserved1 = models.CharField(max_length=50, blank=True, null=True, default='')
    reserved2 = models.CharField(max_length=50, blank=True, null=True, default='')

    # status
    hunting_status = models.IntegerField(blank=True, null=True, choices=HUNTING_STATUS_CHOICES)

    # ai info
    callInstanceId = models.CharField(max_length=50, blank=True, null=True)
    callPhoneDuration = models.CharField(max_length=100, blank=True, null=True)
    callTags = models.CharField(max_length=100, blank=True, null=True)
    callJobname = models.CharField(max_length=100, blank=True, null=True)

    # table related info
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__ (self):
        return self.username

class Education(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default='')
    start = models.DateField(blank=True, null=True)
    end = models.DateField(blank=True, null=True)

    # basic info
    school = models.CharField(max_length=50, blank=True, null=True)
    college = models.CharField(max_length=50, blank=True, null=True)
    major = models.CharField(max_length=50, blank=True, null=True)
    degree = models.IntegerField(choices=DEGREE_CHOICES, blank=True, null=True)
    edu_type = models.CharField(max_length=50, choices=EDUCATION_TYPE_CHOICES, blank=True, null=True)

    # resident info
    province = models.CharField(max_length=10, blank=True, null=True)
    city = models.CharField(max_length=10, blank=True, null=True)
    district = models.CharField(max_length=10, blank=True, null=True)
    street = models.CharField(max_length=20, blank=True, null=True)
    place = models.CharField(max_length=50, blank=True, null=True)

    instructor = models.CharField(max_length=50, blank=True, null=True)
    instructor_phone = models.CharField(max_length=15, null=True, blank=True)

    # table related info
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.degree

class Tag(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, default='')
    recuriter = models.CharField(max_length=50, blank=True, null=True)
    tag = models.CharField(max_length=50, blank=True, null=True)

    # table related info
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

web_codes/recruit_manager/templates/recruit_manager/basic_header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Recruit Panel - Basic</title>

    <!-- Custom fonts for this template -->
    <link href="{% static 'recruit_manager/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'recruit_manager/css/nunito.css' %}" ref="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'recruit_manager/css/sb-admin-2.css' %}" rel="stylesheet">


    <!-- For resume info -->
    <!-- Google Font -->
    <link href="{% static 'recruit_manager/css/roboto.css' %}" rel="stylesheet">

    <!-- FontAwesome JS-->
    <script src="{% static 'recruit_manager/js/fontawesome.all.js' %}"> </script>

    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static 'recruit_manager/css/pillar-1.css' %}">
    <link id="breadcrumb-style" rel="stylesheet" href="{% static 'recruit_manager/css/breadcrumb_1.css' %}">
    <link id="messagebox-style" rel="stylesheet" href="{% static 'recruit_manager/css/messagebox.css' %}">

    <!-- timekeeper -->
    <link id="ordov-timekeeper-style" rel="stylesheet" href="{% static 'recruit_manager/css/jquery.timepicker.min.css' %}">
    <link id="ordov-datekeeper-style" rel="stylesheet" href="{% static 'recruit_manager/css/jquery-ui.css' %}">

</head>

web_codes/recruit_manager/templates/recruit_manager/basic_js.html
{% load static %}
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'recruit_manager/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'recruit_manager/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'recruit_manager/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'recruit_manager/js/sb-admin-2.min.js' %}"></script>

  <!-- -->
  <script src="{% static 'recruit_manager/js/resume_edit.js' %}"></script>
  <script src="{% static 'recruit_manager/js/resume_education_edit.js' %}"></script>
  <script src="{% static 'recruit_manager/js/resume_project_edit.js' %}"></script>
  <script src="{% static 'recruit_manager/js/resume_language_edit.js' %}"></script>
  <script src="{% static 'recruit_manager/js/resume_certification_edit.js' %}"></script>

  <!-- timepicker.min.js -->
  <script src="{% static 'recruit_manager/js/jquery.timepicker.min.js' %}"></script>

  <!-- sidebar -->
  <script src="{% static 'recruit_manager/js/jquery.sidebar.js' %}"></script>
  <script src="{% static 'recruit_manager/js/handlers.js' %}"></script>

  <!-- multiselect -->
  <script src="{% static 'recruit_manager/js/jquery.multiselect.js' %}"></script>

  <!-- jquery-ui.js now for date-keeper -->
  <script src="{% static 'recruit_manager/js/jquery-ui.js' %}"></script>

  <!-- layui.js/xadmin.js now for layui -->
  <script src="{% static 'recruit_manager/js/layui/layui.js' %}"></script>
  <script src="{% static 'recruit_manager/js/xadmin.js' %}"></script>

web_codes/recruit_manager/templates/recruit_manager/detail_resume.html
{% load static %}
{% include 'recruit_manager/basic_header.html' %}

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    {% include 'recruit_manager/basic_sidebar.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- BEGIN -->
        {% include 'recruit_manager/detail_resume_inner.html' %}
        <!--  STOP -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{{ t_resume_detail.username }}</h1>
          </div>

          <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        {% include 'recruit_manager/basic_footer.html' %}

      </div>
      <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    {% include 'recruit_manager/basic_logout.html' %}

    {% include 'recruit_manager/basic_js.html' %}

</body>

</html>

web_codes/recruit_manager/templates/recruit_manager/interview_api.html
{% load static %}
{% include 'recruit_manager/basic_header.html' %}

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">

              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-left">
                    <h1 class="h4 text-gray-900 mb-4">Simulation Of Interview: {{ t_interview.status }}</h1>
                  </div>
                  <form class="user "action={% url 'app_manager:t_interview_result' t_interview.id %} method='GET'>

                      <div class="form-group">
                        <input type="text" class="form-control" id="apiName" aria-describedby="Username" placeholder={{ t_resume.username }}>
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control" id="apiPhone" placeholder={{ t_resume.phone_number }}>
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control" id="apiEmail" placeholder={{ t_resume.email }}>
                      </div>

                      {% if t_interview.status == 0 %}
                      <button class="btn btn-info btn-icon-split border-0" id="stage">
                        <span class="icon text-white-50">
                          <i class="fas fa-arrow-right"></i>
                        </span>
                        <span class="text">开始预约联系人</span>
                      </button>
                      {% elif t_interview.status == 1 %}
                      <div class="form-group">
                        <input type="text" class="form-control" id="text_result" placeholder="填写意见">
                      </div>
                      <button class="btn btn-info btn-icon-split border-0" id="stage">
                        <span class="icon text-white-50">
                          <i class="fas fa-arrow-right"></i>
                        </span>
                        <span class="text">面试前沟通结束</span>
                      </button>
                      {% elif t_interview.status < 5 %}
                      <div class="form-group">
                        <input type="text" class="form-control" id="text_result" placeholder="填写意见">
                      </div>
                      <button class="btn btn-info btn-icon-split border-0" id="stage">
                        <span class="icon text-white-50">
                          <i class="fas fa-arrow-right"></i>
                        </span>
                        <span class="text">面试结束</span>
                      </button>
                      {% elif t_interview.status == 5 %}
                      <div class="form-group">
                        <input type="text" class="form-control" id="text_result" placeholder="OFFER详情">
                      </div>
                      <button class="btn btn-info btn-icon-split border-0" id="stage">
                        <span class="icon text-white-50">
                          <i class="fas fa-arrow-right"></i>
                        </span>
                        <span class="text">发放OFFER</span>
                      </button>
                      {% endif %}
                    <hr>
                  </form>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  {% include 'recruit_manager/basic_js.html' %}

</body>

</html>

web_codes/recruit_manager/templates/recruit_manager/invitation_api.html
{% load static %}
{% include 'recruit_manager/basic_header.html' %}

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">

              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-left">
                    <h1 class="h4 text-gray-900 mb-4">Simulation Of AI Interface For Invitation Candidate</h1>
                  </div>
                  <form class="user "action={% url 'app_manager:t_invitation_result' t_resume.id %} method='GET'>

                    <div class="form-group">
                      <input type="text" class="form-control" id="apiName" aria-describedby="Username" placeholder={{ t_resume.username }}>
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control" id="apiPhone" placeholder={{ t_resume.phone_number }}>
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control" id="apiEmail" placeholder={{ t_resume.email }}>
                    </div>

                    <button class="btn btn-info btn-icon-split border-0" id="stage">
                      <span class="icon text-white-50">
                        <i class="fas fa-arrow-right"></i>
                      </span>
                      <span class="text">Inviate Candidate...</span>
                    </button>
                    <hr>
                  </form>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  {% include 'recruit_manager/basic_js.html' %}

</body>

</html>

web_codes/recruit_manager/templates/recruit_manager/perm.html
<div id="perm" style="border:3px solid white; margin-top:10px; margin-left:3px; margin-right:3px;padding:5px;margin:0px; height=1000px">
  <div style="display:block; margin:2px;padding:2px;">
    <?-- Post -->
    <h5 style="margin:-1;">
    <button id="text_company_name2" class="btn btn-link" data-toggle="collapse" data-target="#collapsePost" aria-expanded="true" aria-controls="collapsePost" style="display:block;">
        权限管理:
    <span id="projPermName"></span>
    </button>
    </h5>

    <div class="container" style="border:3px solid white">
      <div>
        <span><h6 style="color:#b08c21;"> 设置面试阶段负责人</h6></span>
      </div>

      <div>
        <div class="input-group">
          <div class="">
            <span class="" id="" style="width:55px">阶段</span>
          </div>
          <select class="active" id="interview_stage_id" multiple="multiple" name="stage_stage">
            <option value=0>待筛选</option>
            <option value=1>筛选</option>
            <option value=2>邀约</option>
            <option value=3>面试</option>
            <option value=4>Offer</option>
            <option value=5>入职</option>
            <option value=6>考察</option>
            <option value=7>回款</option>
            <option value=8>完成</option>
            <option value=-1>不合适</option>
          </select>
        </div>
      </div>

      <div>
        <div class=" input-group">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1" style="width:55px">责任人</span>
          </div>
          <select class="form-control" id="cRecruiter" name="response" aria-labelledby="basic-addon1">
          </select>
        </div>
      </div>

      <div>
        <div class=" input-group">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1" style="width:55px">操作</span>
          </div>
          <select class="form-control" id="permOp" name="permOp" aria-labelledby="basic-addon1">
            <option></option>
            <option>增加</option>
            <option>删除</option>
          </select>
        </div>
      </div>
    </div> <?-- container -->
    <div style="border:3px solid white;height:250px;">
        <span><h6 style="color:#b08c21;">当前的权限信息</h6></span>
        <textarea id="projPermInfo" style="margin-left:auto; font-size:20px; height:200px"></textarea>
    </div>
    <div style="border:3px">
    </div>

  </div>
</div>

web_codes/recruit_manager/templates/recruit_manager/table_basic.html
{% load static %}
{% include 'recruit_manager/table_header.html' %}
<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    {% include 'recruit_manager/basic_sidebar.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Begin Page Content -->

          <!-- Page Heading -->
          <!-- <h1 class="h3 mb-2 text-gray-800">{{ template_table_name }}</h1> -->
          <!--
               <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p>
          -->
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3" style="display:none;">
              <h6 class="m-0 font-weight-bold text-primary">Details</h6>
            </div>
            <div class="card-body">
              {% block content %} {% endblock %}
            </div>
          </div>

        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      {% include 'recruit_manager/basic_footer.html' %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  {% include 'recruit_manager/basic_logout.html' %}

  {% include 'recruit_manager/basic_js.html' %}

  <!-- Page level plugins -->
  <script src="{% static 'recruit_manager/js/datatables.min.js' %}"></script>
  <script src="{% static 'recruit_manager/js/scrolling.js' %}"></script>
  <script src="{% static 'recruit_manager/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'recruit_manager/vendor/datatables/dataTables.checkboxes.min.js' %}"></script>
  <script src="{% static 'recruit_manager/js/bootstrap-datetimepicker.js' %}"></script>
  <script src="{% static 'recruit_manager/js/bootstrap-datetimepicker.fr.js' %}"></script>

  <script src="{% static 'recruit_manager/js/bootstrap-select.min.js' %}"></script>

  <!-- Page level custom scripts -->
  {% block extra_js %} {% endblock %}
</body>

</html>

web_codes/recruit_manager/templates/recruit_manager/table_candidates.html
{% extends "recruit_manager/table_basic.html" %}
{% load static %}
{% block content %}
<div class="table-responsive">
  <table class="table table-striped " id="dataTable" width="100%" cellspacing="0">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Gender</th>
        <th>School</th>
        <th>Degree</th>
        <th>Major</th>
        <th>status</th>
      </tr>
    </thead>
    {% if t_candidate_list %}
    <tbody>
      {% for candidate in t_candidate_list %}
      <tr>
        <td>
          <a href="{% url 'app_manager:t_resume' candidate.resume_set.first.id %}">
            {{ candidate.id }}
          </a>
        </td>
        <td>{{ candidate.resume_set.first.username }} </td>
        <td>
          {% if candidate.resume_set.first.gender == 'm' %}
          Male
          {% else %}
          Female
          {% endif %}
        </td>
        <td>{{ candidate.resume_set.first.school }} </td>
        <td>{{ candidate.resume_set.first.degree }} </td>
        <td>{{ candidate.resume_set.first.major }} </td>
        <td>
          {% if candidate.interview_set.all.count > 0 or candidate.interviewed %}
          <button class="btn btn-success btn-icon-split border-0" id="stage">
            <span class="icon text-white-50">
              <i class="fas fa-check"></i>
            </span>
            <span class="text">Interviewed</span>
          </button>
          {% else %}
          <form action={% url 'app_manager:t_interview_api' candidate.id %} method='GET'>
            <button class="btn btn-info btn-icon-split border-0" id="stage">
              <span class="icon text-white-50">
                <i class="fas fa-arrow-right"></i>
              </span>
              <span class="text">Prepare Interview</span>
            </button>
          </form>
          {% endif %}
        </td>

      </tr>
      {% endfor %}
    </tbody>
    {% endif %}
  </table>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'recruit_manager/js/demo/datatables-demo.js' %}"></script>
{% endblock%}