web_codes/ordov/urls.py
from django.contrib import admin
from django.urls import include, path
from candidates import views as candidatesViews
from resumes import views as resumesViews
from accounts import views as accountsViews
from companies import views as companiesViews
from interviews import views as interviewsViews
from experiences import views as experiencesViews
from permissions import views as permissionsViews

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'resumes', resumesViews.ResumeViewSet)
router.register(r'candidates', candidatesViews.CandidateViewSet)
router.register(r'posts', companiesViews.PostViewSet)
router.register(r'interviews', interviewsViews.InterviewViewSet)
router.register(r'experiences', experiencesViews.ExperienceViewSet)
router.register(r'educations', resumesViews.EducationViewSet)
router.register(r'projects', experiencesViews.ProjectViewSet)
router.register(r'languages', experiencesViews.LanguageViewSet)
router.register(r'certifications', experiencesViews.CertificationViewSet)
router.register(r'permissions', permissionsViews.ProjectPermissionViewSet)
router.register(r'accounts', accountsViews.UserProfileViewSet)
router.register(r'tags', resumesViews.TagViewSet)

# Look at here: all path pattern should be ENDUP with '/'
urlpatterns = [
    path('accounts/signup/', accountsViews.signup, name='accounts_signup'),
    path('accounts/signin/', accountsViews.signin, name='accounts_signin'),
    path('process/', accountsViews.process, name='process'),
    path('accounts/login/', accountsViews.MyLoginView.as_view(), name='login'),
    path('accounts/', include('allauth.urls')),
    path('api/v1/getResult', interviewsViews.aiTest),
    path('candidates/resume/update/', candidatesViews.updateResume, name='candidate_update_resume'),
    path('candidates/resume/success/', candidatesViews.apply_success, name='candidate_apply_success'),

    path('admin/', admin.site.urls),

    path('', include('landing_page.urls')),

    path('manager/', include('recruit_manager.urls'), name='manager'),
    path('company/', include('recruit_company.urls'), name='company'),
    path('applicant/', include('recruit_applicant.urls'), name='applicant'),

    path('api/', include(router.urls)),
    path('post/post/update/', companiesViews.UpdatePost),
    path('interview/ai/update/', interviewsViews.UpdateAIStatus),
    path('interview/ai/task/', interviewsViews.Task),
    path('interview/ai/info/', interviewsViews.getAIInfo),

    path('interviews/', include('interviews.urls'))
]

web_codes/recruit_applicant/urls.py
from django.urls import path

from recruit_applicant import views

app_name = 'app_applicant'
urlpatterns = [
    path('', views.index, name='t_index'), # t_index will be used in template
]

web_codes/recruit_manager/urls.py
from django.urls import path

from recruit_manager import views
from resumes import views as resumesViews
from companies import views as companiesViews
from interviews import views as interviewsViews

app_name = 'app_manager'

# Look at Here!! : All path pattern should be ENDUP with '/'
urlpatterns = [
    # ex: /manager/
    path('', views.index, name='t_index'), # t_index will be used in template
    path('upload/', views.upload, name='t_upload'),
    path('candidates/', views.CandidateTable.as_view(), name='t_candidates'),

    path('interviews/', interviewsViews.InterviewTable.as_view(), name='t_interviews'),

    path('interview-api/<int:resume_id>/<int:interview_id>/', views.interview_api, name='t_interview_api'),
    path('interview-result/<int:interview_id>/', views.interview_result, name='t_interview_result'),

    path('invitation-api/<int:resume_id>/', views.invitation_api, name='t_invitation_api'),
    path('invitation-result/<int:resume_id>/', views.invitation_result, name='t_invitation_result'),
    path('resumes/statistic/<int:post_id>/', views.resume_statistic, name='t_resume_statistic'),


    path('resumes/', resumesViews.ResumeTable.as_view(), name='t_resumes'),
    path('multi/', resumesViews.MultiTable.as_view(), name='t_multi'),
    path('multi/callInterview', views.callInterview, name='t_callInterview'),
    path('multi/test', views.callInterview, name='t_callInterview'),
    path('composite/', resumesViews.CompositeTable.as_view(), name='t_composite'),
    path('resumes/<int:pk>/', resumesViews.ResumeDetailInfo, name='t_resume'),
    path('resumes/<int:pk>/edit/', resumesViews.ResumeDetailInfo, name='t_resume_edit'),
    path('posts/', companiesViews.PostTable.as_view(), name='t_posts'),
]

web_codes/recruit_applicant/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {}
    return render(request, 'recruit_applicant/index.html', context)

web_codes/recruit_applicant/templates/recruit_applicant/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Landing Page - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'recruit_applicant/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  {% include 'landing_page/font.html' %}
  <link href="{% static 'recruit_applicant/vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template -->
  <link href="{% static 'recruit_applicant/css/landing-page.css' %}" rel="stylesheet">
  <link href="{% static 'landing_page/css/one-page-wonder.css' %}" rel="stylesheet">
</head>

<body>

  {% include 'landing_page/nav.html' %}

  <!-- Masthead -->
  <header class="masthead text-white text-center">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">Welcome Aboard!</h1>
          <h3 class="lead mb-0">SITENAME makes searching jobs easy</h3>
        </div>
      </div>
    </div>
  </header>

  <!-- Icons Grid -->
  <section class="features-icons bg-light text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-layers m-auto text-primary"></i>
            </div>
            <h3>
              <a href={% url 'candidate_update_resume' %}>写简历</a>
            </h3>
            <p class="lead mb-0"> 更新简历吧，让更多的企业发现你 </p>

          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-screen-desktop m-auto text-primary"></i>
            </div>
            <h3>
              <a href={% url 'app_manager:t_resumes' %}>查看简历</a>
            </h3>
            <p class="lead mb-0">检查并确认你的简历信息</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-check m-auto text-primary"></i>
            </div>
            <h3>
              <a href={% url 'app_manager:t_posts' %}>找工作</a>
            </h3>
            <p class="lead mb-0"> 查看适合的工作岗位 </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Image Showcases -->
  <section class="showcase">
    <div class="container-fluid p-0">
      <div class="row no-gutters">

        <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url({% static 'recruit_applicant/img/bg-showcase-2.jpg' %});"></div>
        <div class="col-lg-6 order-lg-1 my-auto showcase-text">
          <h2>Online Interview Schedule</h2>
          <p class="lead mb-0">SITENAME is an advanced recruite platform for the under gradute or fresh man with a job experience within five years. SITENAME is your home, where you can communicate with your contemporary. Have a nice time in SITETIME.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer class="footer bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
          <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2019. All Rights Reserved.</p>
        </div>
        <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
          <ul class="list-inline mb-0">
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-facebook fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-twitter-square fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-instagram fa-2x fa-fw"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'recruit_applicant/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'recruit_applicant/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>