web_codes/landing_page/urls.py
from django.urls import path

from landing_page import views

app_name = 'app_landing'
urlpatterns = [
    # ex: /landing_page/
    path('', views.index, name='t_index'), # t_index will be used in template
]

web_codes/ordov/urls.py
from django.contrib import admin
from django.urls import include, path
from candidates import views as candidatesViews
from resumes import views as resumesViews
from accounts import views as accountsViews
from companies import views as companiesViews
from interviews import views as interviewsViews
from experiences import views as experiencesViews
from permissions import views as permissionsViews

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'resumes', resumesViews.ResumeViewSet)
router.register(r'candidates', candidatesViews.CandidateViewSet)
router.register(r'posts', companiesViews.PostViewSet)
router.register(r'interviews', interviewsViews.InterviewViewSet)
router.register(r'experiences', experiencesViews.ExperienceViewSet)
router.register(r'educations', resumesViews.EducationViewSet)
router.register(r'projects', experiencesViews.ProjectViewSet)
router.register(r'languages', experiencesViews.LanguageViewSet)
router.register(r'certifications', experiencesViews.CertificationViewSet)
router.register(r'permissions', permissionsViews.ProjectPermissionViewSet)
router.register(r'accounts', accountsViews.UserProfileViewSet)
router.register(r'tags', resumesViews.TagViewSet)

# Look at here: all path pattern should be ENDUP with '/'
urlpatterns = [
    path('accounts/signup/', accountsViews.signup, name='accounts_signup'),
    path('accounts/signin/', accountsViews.signin, name='accounts_signin'),
    path('process/', accountsViews.process, name='process'),
    path('accounts/login/', accountsViews.MyLoginView.as_view(), name='login'),
    path('accounts/', include('allauth.urls')),
    path('api/v1/getResult', interviewsViews.aiTest),
    path('candidates/resume/update/', candidatesViews.updateResume, name='candidate_update_resume'),
    path('candidates/resume/success/', candidatesViews.apply_success, name='candidate_apply_success'),

    path('admin/', admin.site.urls),

    path('', include('landing_page.urls')),

    path('manager/', include('recruit_manager.urls'), name='manager'),
    path('company/', include('recruit_company.urls'), name='company'),
    path('applicant/', include('recruit_applicant.urls'), name='applicant'),

    path('api/', include(router.urls)),
    path('post/post/update/', companiesViews.UpdatePost),
    path('interview/ai/update/', interviewsViews.UpdateAIStatus),
    path('interview/ai/task/', interviewsViews.Task),
    path('interview/ai/info/', interviewsViews.getAIInfo),

    path('interviews/', include('interviews.urls'))
]

web_codes/recruit_applicant/urls.py
from django.urls import path

from recruit_applicant import views

app_name = 'app_applicant'
urlpatterns = [
    path('', views.index, name='t_index'), # t_index will be used in template
]

web_codes/recruit_manager/urls.py
from django.urls import path

from recruit_manager import views
from resumes import views as resumesViews
from companies import views as companiesViews
from interviews import views as interviewsViews

app_name = 'app_manager'

# Look at Here!! : All path pattern should be ENDUP with '/'
urlpatterns = [
    # ex: /manager/
    path('', views.index, name='t_index'), # t_index will be used in template
    path('upload/', views.upload, name='t_upload'),
    path('candidates/', views.CandidateTable.as_view(), name='t_candidates'),

    path('interviews/', interviewsViews.InterviewTable.as_view(), name='t_interviews'),

    path('interview-api/<int:resume_id>/<int:interview_id>/', views.interview_api, name='t_interview_api'),
    path('interview-result/<int:interview_id>/', views.interview_result, name='t_interview_result'),

    path('invitation-api/<int:resume_id>/', views.invitation_api, name='t_invitation_api'),
    path('invitation-result/<int:resume_id>/', views.invitation_result, name='t_invitation_result'),
    path('resumes/statistic/<int:post_id>/', views.resume_statistic, name='t_resume_statistic'),


    path('resumes/', resumesViews.ResumeTable.as_view(), name='t_resumes'),
    path('multi/', resumesViews.MultiTable.as_view(), name='t_multi'),
    path('multi/callInterview', views.callInterview, name='t_callInterview'),
    path('multi/test', views.callInterview, name='t_callInterview'),
    path('composite/', resumesViews.CompositeTable.as_view(), name='t_composite'),
    path('resumes/<int:pk>/', resumesViews.ResumeDetailInfo, name='t_resume'),
    path('resumes/<int:pk>/edit/', resumesViews.ResumeDetailInfo, name='t_resume_edit'),
    path('posts/', companiesViews.PostTable.as_view(), name='t_posts'),
]

web_codes/landing_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {}
    return render(request, 'landing_page/index.html', context)

web_codes/landing_page/templates/landing_page/font.html
{% load static %}
<link href="{% static 'landing_page/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Merriweather:300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

web_codes/landing_page/templates/landing_page/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SITENAME</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'landing_page/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  {% include 'landing_page/font.html' %}
  <!-- Custom styles for this template -->
  <link href="{% static 'landing_page/css/coming-soon.css' %}" rel="stylesheet">
  <link href="{% static 'landing_page/css/one-page-wonder.css' %}" rel="stylesheet">
</head>

<body>
  <!-- temporarily workaround the scrollbar shift issue -->
  <div style="padding-left: 54px;height:1px">
  </div>

  {% include 'landing_page/nav.html' %}

  <div class="overlay"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="{% static 'landing_page/mp4/bg.mp4' %}" type="video/mp4">
  </video>

  <div class="masthead">
    <div class="masthead-bg"></div>
    <div class="container h-100">
      <div class="row h-100">
        <div class="col-12 my-auto">
          <div class="masthead-content text-white py-5 py-md-0">
            <h1 class="mb-3"> 搜寻 </h1>
            <p class="mb-5">
              伟大的公司需要伟大的员工 <br>
              实现伟大的目标!<br>
              这里有 <strong>15000+</strong> 岗位等着你!
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="social-icons">
    <ul class="list-unstyled text-center mb-0">
      <li class="list-unstyled-item">
        <a href="#">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
      <li class="list-unstyled-item">
        <a href="#">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
      <li class="list-unstyled-item">
        <a href="#">
          <i class="fab fa-instagram"></i>
        </a>
      </li>
    </ul>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'landing_page/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'landing_page/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'landing_page/js/coming-soon.min.js' %}"></script>

</body>

</html>

web_codes/landing_page/templates/landing_page/nav.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'app_landing:t_index' %}">ALL-IN招聘管理系统</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app_applicant:t_index' %}">应聘者</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">企业</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app_manager:t_index' %}">管理员</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">联系我们</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">关于</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/accounts/signin/">登录</a>
        </li>
      </ul>
    </div>
  </div>
</nav>